version: '3'
services:
  mongodb:  # База данных
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file: backend/.env
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  backend:
    build:
      context: backend/
    container_name: backend
    env_file: backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: frontend/
    container_name: frontend
    ports:
      - "3000:80"

  tests:  # Заполнение БД тестовыми данными
    build:
      context: backend/
      dockerfile: Dockerfile.populate
    container_name: populate
    env_file: backend/.env
    depends_on:
      - frontend